# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('created_at', models.DateField()),
                ('size', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='subdirectory/to-upload/my-images')),
            ],
        ),
    ]
