# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my.imageUpload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='subdirectory/No-img.jpg', upload_to='subdirectory/to-upload/my-images'),
        ),
    ]
