# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my.imageUpload', '0002_auto_20171024_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_format',
            field=models.CharField(default='PNG', max_length=1500),
            preserve_default=False,
        ),
    ]
